### ISSUE TITLE
Support for installations that have moved their folders from the base directory

### ISSUE THREAD

**Issue by Foroneus** [uwx/PlayniteMultiMCLibrary#1]
Scanning the folder where MultiMC.exe is will find nothing if you've moved your instances to another folder., and scanning that folder instead will give you the instances but no way to launch them. Could you add an option that lets people with a setup like this specify where MultiMC.exe is so that they can launch it (and if it's blank, it can continue its current behavior)?

**Comment by uwx** [comment]
Added in 1.2. I haven't been able to fully test this as I haven't played Minecraft in a while and my account isn't linked to a Microsoft account, but it seems to work.
