### ISSUE TITLE
Feature request: Add support for PolyMC

### ISSUE THREAD

**Issue by AutumnRivers** [uwx/PlayniteMultiMCLibrary#3]
[PolyMC](https://github.com/PolyMC/PolyMC) is a fork of MultiMC, made by the community after disagreements arose between the community and MultiMC devs.

As of writing this issue, Playnite will crash when loading the PolyMC folder as it can't find `multimc.cfg`, since PolyMC uses `polymc.cfg`. Making a copy of the PolyMC file and renaming the copy to `multimc.cfg` works just fine, but it would be awesome to have Poly supported by default. The extension will also fail to load any instances, as it tries to launch `MultiMC.exe`, when Poly is `PolyMC.exe`.

Besides the filename differences, Multi and Poly function the same. I do hope this wouldn't require too much work!

**Comment by uwx** [comment]
Will fix this when I have time, however this should be pretty easy to implement if anyone wants to do so.

**Comment by Team-Hufflepuff** [comment]
I would love to see this too!

**Comment by uwx** [comment]
Added, but I didn't fully test it, let me know if anything breaks.

**Comment by uwx** [comment]
Right, I only tested this with a portable installation. I'll have to add support for non-portable installs.

**Comment by GMRobo** [comment]
> Right, I only tested this with a portable installation. I'll have to add support for non-portable installs.

I also have a portable version, but the extension fails to import the instances. I click for it to update the game library, it'll say library update finished, and nothing shows up under the library "MultiMC/PolyMC" (nor does a search for the instance name yield any results). I double checked that the path to poly is correct and it still failed. <sub>I mean, hey at least it's not crashing anymore <sub>

**Comment by AutumnRivers** [comment]
> I also have a portable version, but the extension fails to import the instances. I click for it to update the game library, it'll say library update finished, and nothing shows up under the library "MultiMC/PolyMC" (nor does a search for the instance name yield any results). I double checked that the path to poly is correct and it still failed. I mean, hey at least it's not crashing anymore

What's your path to your PolyMC? Mine is working fine.

**Comment by uwx** [comment]
Portable install support added in c47d0a4. Hopefully for good this time.

> I also have a portable version, but the extension fails to import the instances. I click for it to update the game library, it'll say library update finished, and nothing shows up under the library "MultiMC/PolyMC" (nor does a search for the instance name yield any results). I double checked that the path to poly is correct and it still failed. I mean, hey at least it's not crashing Playnite anymore

Make sure the path in the settings is pointing folder that *contains* the PolyMC.exe file, not the file itself. Also try updating to 1.4 and see if anything changes. If not, reply with your Playnite extension.log and playnite.log, as well as your polymc.cfg file.

**Comment by GMRobo** [comment]
> Portable install support added in [c47d0a4](https://github.com/uwx/PlayniteMultiMCLibrary/commit/c47d0a43e4089c760922e41dcf2b6870bb5dcfc9). Hopefully for good this time.
> 
> > I also have a portable version, but the extension fails to import the instances. I click for it to update the game library, it'll say library update finished, and nothing shows up under the library "MultiMC/PolyMC" (nor does a search for the instance name yield any results). I double checked that the path to poly is correct and it still failed. I mean, hey at least it's not crashing Playnite anymore
> 
> Make sure the path in the settings is pointing folder that _contains_ the PolyMC.exe file, not the file itself. Also try updating to 1.4 and see if anything changes. If not, reply with your Playnite extension.log and playnite.log, as well as your polymc.cfg file.

Ah, so that was the problem, the extension pointed to the ...\poly 1.3.1\instance folder by default. so i had assumed that was what was required. i am not the most knowledgeable in coding 😄
