### ISSUE TITLE
Add Prism support

### ISSUE THREAD

**Issue by skullbone** [uwx/PlayniteMultiMCLibrary#6]
Well, to say the least, polymc fell apart and the majority of the people behind polymc were kicked from it, so they forked it and made prism it should pretty much be exactly the same. I renamed the exe and .cfg to polymc, and it worked. Simple workaround but proper support would be nice. PrismLauncher: https://github.com/PrismLauncher/PrismLauncher

**Comment by uwx** [comment]
PRs welcome, I can't keep up with every time the lead developer of a project has a "gamer moment"

**Comment by skullbone** [comment]
Yeah, fair I thought about trying to fix it myself and I tried but I have no clue what I'm doing.

**Comment by N0tJust1n** [comment]
@skullbone 

Could you manually try this pext to confirm it is functioning properly?

[https://github.com/N0tJust1n/PlaynitePrismMCLibrary/blob/master/PlayniteMultiMCLibrary/Packed/MultiMClibrary_6ab2531e-4800-404b-a938-4421b28a9f3e_1_5.pext?raw=true](https://github.com/N0tJust1n/PlaynitePrismMCLibrary/blob/master/PlayniteMultiMCLibrary/Packed/MultiMClibrary_6ab2531e-4800-404b-a938-4421b28a9f3e_1_5.pext?raw=true)
